# Streamlit Configuration for LinkedInPostMaster

[theme]
primaryColor = "#0077B5"  # LinkedIn Blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6F8"
textColor = "#000000"
font = "sans serif"

[server]
# Production settings
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
